Tweak update_site_status to accept multiple sites
I'm not using this functionality right now, but down the line it would
be nice to be able to add sites easily.

diff --git a/.local/bin/update-site-status b/.local/bin/update-site-status
--- a/.local/bin/update-site-status
+++ b/.local/bin/update-site-status
@@ -1,13 +1,21 @@
 #!/usr/bin/env bash
 
-SITE="$1"
 CACHE_DIR=${XDG_CACHE_HOME:-/home/julian/.cache}
 
-output="$(curl -sL -w "%{http_code}\\n" "https://$SITE" -o /dev/null)"
-if [ ! $? -eq 0 ]; then
-  echo "update-site-status failed for $SITE"
-  exit 1
-fi
+update_site_status() {
+  local site="$1"
+  local output="$(curl -sL -w "%{http_code}\\n" "https://$site" -o /dev/null)"
+  if [ ! $? -eq 0 ]; then
+    echo "update-site-status failed for $site"
+    exit 1
+  fi
 
-mkdir -p "$CACHE_DIR/site-status"
-echo -n "$output" > "$CACHE_DIR/site-status/$SITE"
+  mkdir -p "$CACHE_DIR/site-status"
+  echo -n "$output" > "$CACHE_DIR/site-status/$site"
+}
+
+for site in "$@"; do
+  update_site_status $site &
+done
+
+wait
